/**
 * Domain types — Single Source of Truth for all type definitions.
 *
 * ‐ `DbPromptRow` is derived from `database.types.ts` (auto-generated by Supabase CLI).
 * ‐ `Prompt` is the client-side model used by UI components.
 * ‐ All other domain types (Phase, Folder, SortOrder, etc.) live here.
 */
import type { Tables } from "@/lib/database.types";

/* ─── DB Row types (auto-generated source) ─── */
export type DbPromptRow = Tables<"prompts"> & {
  /** Joined from profiles via Supabase select */
  profiles?: { display_name: string | null; avatar_url: string | null }[] | null;
};

export type DbFolderRow = Tables<"folders">;

/* ─── Domain types ─── */
export type Phase = "All" | "Planning" | "Design" | "Implementation" | "Debug" | "Release" | "MVP" | "Memo" | "Other";

export interface Prompt {
  id: string;
  title: string;
  content: string;
  tags: string[];
  phase: Exclude<Phase, "All">;
  visibility: "Private" | "Public";
  updatedAt: string;
  likeCount: number;
  useCount?: number;
  isPinned?: boolean;
  authorId?: string;
  authorName?: string;
  authorAvatarUrl?: string;
  folderId?: string;
  lastUsedAt?: string;
  notes?: string;
  rating?: "good" | "neutral" | "bad";
}

export interface Folder {
  id: string;
  name: string;
  color: string;
  sortOrder: number;
}

export type SortOrder = "updated" | "created" | "useCount" | "likes" | "title";

export const SORT_OPTIONS: { value: SortOrder; label: string }[] = [
  { value: "updated", label: "更新日順" },
  { value: "useCount", label: "よく使う順" },
  { value: "likes", label: "いいね順" },
  { value: "title", label: "タイトル順" },
];

export interface HistoryEntry {
  timestamp: string;
  title: string;
  content: string;
  label?: string;
}

export interface AppNotification {
  id: string;
  type: "like" | "favorite";
  promptId: string;
  promptTitle: string;
  actorName: string;
  timestamp: string;
  read: boolean;
}

/* ─── Phase constants (moved from mock-data.ts) ─── */
export interface PhaseInfo {
  id: Phase;
  label: string;
  icon: string;
  hint: string;
}

export const PHASES: PhaseInfo[] = [
  { id: "All", label: "すべて", icon: "🏠", hint: "全フェーズのプロンプト" },
  { id: "Planning", label: "企画", icon: "🌱", hint: "アイデアを整理するとき" },
  { id: "Design", label: "設計", icon: "🎨", hint: "画面や構成を考えるとき" },
  { id: "Implementation", label: "実装", icon: "💻", hint: "コードを書くとき" },
  { id: "Debug", label: "デバッグ", icon: "🐛", hint: "エラーを直すとき" },
  { id: "Release", label: "リリース", icon: "🚀", hint: "公開するとき" },
  { id: "MVP", label: "MVP", icon: "🏆", hint: "最小限の機能で検証するとき" },
  { id: "Memo", label: "memo", icon: "📝", hint: "メモ・覚え書き" },
  { id: "Other", label: "その他", icon: "📦", hint: "その他のプロンプト" },
];
